# Define services
services:
  #App backend service
  backend-spring:
    # Configuration for building the docker image for backend service
    build:
      context: backend-spring
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    restart: always
    environment: #Pass environment variables
      - spring.datasource.url=jdbc:mysql://mysql-container:3306/assignmentdb
      - spring.datasource.username=root
      - spring.datasource.password=Susil@123
    depends_on:
      - mysql-container
    networks: # Networks to join
      - db-network
      - frontend-network
  #Frontend Service
  frontend-react:
    build:
      context: frontend-react
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL:   http://backend-spring:8090/
    ports:
      - 80:3000
    restart: always
    depends_on:
      - backend-spring
    networks:
      - frontend-network
  #Database Service (MYSQL)
  mysql-container:
    image: mysql:8.0.28
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: assignmentdb
      MYSQL_ROOT_PASSWORD: Susil@123
      MYSQL_USER: root
      MYSQL_PASSWORD: Susil@123
    networks:
      - db-network
volumes:
  dbdata:
networks:
  db-network:
  frontend-network:
